cancel_monitor_threshold: 3
deal_buy_price: 4660.0
order_monitor_threshold: 3
repeat_close_threshold: 2
repeat_open_threshold: 2
rest_test_price: 168220
rest_test_symbol: LC2607
risk_thresholds:
  max_cancel_count: 5
  max_order_count: 5
  max_symbol_order_count: 3
safe_buy_price: 4630.0
test_symbol: IF2603
volume_limit_volume: 10000
